version: "3"
services:
  db:
    image: postgres:14
    container_name: chess_db
    environment:
      POSTGRES_USER: chess_user
      POSTGRES_PASSWORD: chess_pass
      POSTGRES_DB: chess_stats
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
